general {
    before_sleep_cmd = loginctl lock-session
    lock_cmd = pidof hyprlock || hyprlock       # binary to run when hypridle requests a lock
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after sleep
    ignore_dbus_inhibit = false                 # whether to ignore dbus-sent idle-inhibit requests
}

listener {
    timeout = 150                                # 2.5min.
    on-timeout = brightnessctl set 10%           # set monitor backlight to minimum
    on-resume = brightnessctl set 100%           # monitor backlight restore.
}

listener {
    timeout = 300                                # 5min
    on-timeout = loginctl lock-session           # lock screen
}

listener {
    timeout = 330                                # 5.5min
    on-timeout = hyprctl dispatch dpms off       # screen off
    on-resume = hyprctl dispatch dpms on         # screen on
}

listener {
    timeout = 1800                               # 30min
    on-timeout = systemctl suspend               # suspend pc
}
